### ISSUE TITLE
Sub-exercise not reported in build error messages

### ISSUE THREAD

**Issue by rv2e** [datacamp/shellwhat#32]
@gvwilson commented on [Tue Nov 07 2017](https://github.com/datacamp/learn-bugs/issues/61)

## Summary of the issue

If an SCT contains a syntax error in a BulletConsoleExercise, the build system reports the exercise number but not the sub-exercise number, which makes tracking down the bug less easy.

## Minimally reproducible example

1. Create a BulletConsoleExercise with two or more bullets in a shell course.
2. Create a syntax error in the second or subsequent bullet's SCT.
3. Build.

The build system will report the exercise number (e.g., "Exercise 4") but not which bullet.

## Additional information

Not blocking, but slowing down.

---

@rv2e commented on [Sun Dec 03 2017](https://github.com/datacamp/learn-bugs/issues/61#issuecomment-348816790)

I'll move it to shellwhat and tag it as an enhancement.

**Comment by gvwilson** [comment]
Agreed that it's an enhancement, but is this specific to shell, or does it (not) happen with python course exercises as well? If so, perhaps protowhat rather than shellwhat?

**Comment by machow** [comment]
@rv2e shellwhat does not know the sub-exercise number, so cannot report it. In general the whats / backends don't know anything about exercise numbers. It sounds like an exercise validator (or teach?) issue.

**Comment by filipsch** [comment]
@rv2e as the discussion above states, this is not a shellwhat issue, but an exercise-validator. Moving it there.

**Comment by filipsch** [comment]
Issue moved to [datacamp/exercise-validator #134](https://github.com/datacamp/exercise-validator/issues/134) via [**ZenHub**](https://www.zenhub.com/)
